# DAFTAR ISI
1. pembuatan dataframe pandas
2. mengisi data pada dataframe
3. menambah kolom pada dataframe
4. set_index pada dataframe
5. fungsi rename pada dataframe
6. fungsi drop kolom pada dataframe
7. matematika pertambahan antara kolom
8. matematika pertambahan antar kolom dengan membentuk df diluar dataframe sebelumnya
9. data biasa ke dataframe
10. indexing in array|

In [1]:
import numpy as np  
import pandas as pd 

In [2]:
# pembuatan dataframe pandas
data = pd.DataFrame(columns=['penjualan'])
print(data)

Empty DataFrame
Columns: [penjualan]
Index: []


In [3]:
# mengisi data pada datarame
data['penjualan'] = [123,
                     234, 
                     345,
                     456,
                     567,
                     678,
                     890]
print(data)

   penjualan
0        123
1        234
2        345
3        456
4        567
5        678
6        890


In [4]:
# menambah kolom pada dataframe
data['pemakaian'] = [1232,
                     2342, 
                     3452,
                     4562,
                     5672,
                     6782,
                     8902]
print(data)

   penjualan  pemakaian
0        123       1232
1        234       2342
2        345       3452
3        456       4562
4        567       5672
5        678       6782
6        890       8902


In [5]:
data['nomor'] = [1,
                2,
                3,
                4,
                5,
                6,
                7]
print(data)

   penjualan  pemakaian  nomor
0        123       1232      1
1        234       2342      2
2        345       3452      3
3        456       4562      4
4        567       5672      5
5        678       6782      6
6        890       8902      7


In [6]:
# set_index pada dataframe
dataindex = data.set_index('nomor')
print(dataindex)

       penjualan  pemakaian
nomor                      
1            123       1232
2            234       2342
3            345       3452
4            456       4562
5            567       5672
6            678       6782
7            890       8902


In [7]:
# fungsi rename pada dataframe
datarename = dataindex.rename(columns={"pemakaian":"pemakaian_rename"})
print(datarename)

       penjualan  pemakaian_rename
nomor                             
1            123              1232
2            234              2342
3            345              3452
4            456              4562
5            567              5672
6            678              6782
7            890              8902


In [8]:
# fungsi drop kolom pada dataframe
datadrop = datarename.drop("pemakaian_rename", axis=1)
print(datadrop)

       penjualan
nomor           
1            123
2            234
3            345
4            456
5            567
6            678
7            890


In [9]:
# matematika pertambahan antar kolom 
data['newcolumn'] = data["penjualan"] + data["pemakaian"]
print(data)

   penjualan  pemakaian  nomor  newcolumn
0        123       1232      1       1355
1        234       2342      2       2576
2        345       3452      3       3797
3        456       4562      4       5018
4        567       5672      5       6239
5        678       6782      6       7460
6        890       8902      7       9792


In [10]:
# matematika pertambahan antar kolom dengan membentuk df diluar dataframe sebelumnya
newcolumn = data["penjualan"] + data["pemakaian"]
print(newcolumn)

0    1355
1    2576
2    3797
3    5018
4    6239
5    7460
6    9792
dtype: int64


In [11]:
# konversi data biasa ke dataframe
newcolumndf = pd.DataFrame(newcolumn)
print(newcolumndf)
newcolumnrename = newcolumndf.rename(columns={0:"hasil tambah"})
print(newcolumnrename)

      0
0  1355
1  2576
2  3797
3  5018
4  6239
5  7460
6  9792
   hasil tambah
0          1355
1          2576
2          3797
3          5018
4          6239
5          7460
6          9792


## list_name[start:end]
- start: Indeks elemen pertama yang ingin diambil (inklusif). Jika dikosongkan, dimulai dari awal list.
- end: Indeks elemen terakhir yang ingin diambil (eksklusif). Jika dikosongkan, sampai akhir list.

In [12]:
penjualan = data['penjualan'].values
print(penjualan)

[123 234 345 456 567 678 890]


In [13]:
for i in range(len(penjualan)):
    print(penjualan[i], " = index ke ", i)

123  = index ke  0
234  = index ke  1
345  = index ke  2
456  = index ke  3
567  = index ke  4
678  = index ke  5
890  = index ke  6


In [14]:
data = penjualan[:-3] # mulai dari awal sampai data -3
print(data)

[123 234 345 456]


In [15]:
data = penjualan[:3] # mulai dari awal sampai data ke 3
print(data)

[123 234 345]


In [16]:
data = penjualan[-3:] # mulai dari data -3 belakang sampai akhir
print(data)

[567 678 890]


In [17]:
data = penjualan[3:] # mulai dari data 3 sampai akhir
print(data)

[456 567 678 890]


In [18]:
data = penjualan[2:-1] # mulai dari data 2 sampai data -1
print(data)

[345 456 567 678]
