# RESHAPE

reshape = fungsi dalam Python yang digunakan untuk mengubah bentuk array tanpa mengubah datanya.

## reshape(a,b)
### a = baris, b = kolom
contoh:

In [1]:
import numpy as np
x = [1, 2, 3, 4, 5, 6]
x = np.array(x)

In [2]:
x_reshape2d = x.reshape(2,3) #menjadi 2 baris dengan 3 data per baris.
print(x_reshape2d)

[[1 2 3]
 [4 5 6]]


In [3]:
x_reshape2d = x.reshape(3,2) #menjadi 3 baris dengan 2 data per baris.
print(x_reshape2d)

[[1 2]
 [3 4]
 [5 6]]


In [4]:
x_reshape2d = x.reshape(-1,1) #tidak tahu ingin berapa baris dengan 1 data per baris
print(x_reshape2d)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [5]:
x_reshape2d = x.reshape(1,-1) #ingin satu baris dengan memasukkan semua data kedalamnya
print(x_reshape2d)

[[1 2 3 4 5 6]]


In [6]:
# kembalikan ke bentuk awal

x_unreshape2d = x_reshape2d.reshape(-1) #kembali ke bentuk awal
print(x_unreshape2d)

[1 2 3 4 5 6]


## reshape(a,b,c)
### a = kelompok, b = baris, c = kolom
contoh:

In [7]:
import numpy as np
x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
x = np.array(x)

In [8]:
x_reshape3d = x.reshape(2, 3, 2)  #menjadi 2 kelompok dengan 3 baris dan 2 data disetiap baris
print(x_reshape3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [9]:
x_reshape3d = x.reshape(3, 2, -1)  #menjadi 3 kelompok dengan 2 baris dan terserah berapa data di setiap baris
print(x_reshape3d)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [10]:
x_reshape3d = x.reshape(4, 3, -1)  #menjadi 4 kelompok dengan 3 baris dan terserah berapa data di setiap baris
print(x_reshape3d)

[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]]


In [11]:
# kembalikan ke bentuk awal

x_unreshape3d = x_reshape3d.reshape(-1) #kembali ke bentuk awal
print(x_unreshape3d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


# TERIMA KASIH