In [1]:
import tensorflow as tf
import numpy as np

In [2]:
sess = tf.compat.v1.InteractiveSession()

# Definisi Pada Tensor

In [3]:
a = tf.zeros((2,2))
b = tf.ones((2,2))

print(f"""hasil dari a adalah
{a}""")
print(f"""hasil dari b adalah 
{b}""")

hasil dari a adalah
[[0. 0.]
 [0. 0.]]
hasil dari b adalah 
[[1. 1.]
 [1. 1.]]


# Menghitung Element Pada Tensor

In [4]:
a = tf.constant([[1,1,1], [1,1,1]])

print(a)

# untuk menghitung element yang yang ada pada tensor sebagai berikut
tf.reduce_sum(a)

tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int32)


<tf.Tensor: shape=(), dtype=int32, numpy=6>

# Periksa Bentuk Pada Tensor

In [5]:
a = tf.constant([[1,1,1], [1,1,1]])

a.get_shape()

TensorShape([2, 3])

# Bentuk Ulang Tensor

In [14]:
a = tf.constant([[1,1,1], [1,1,1]])
new = (1, 6)
a_baru = tf.reshape(a, new)

print(a_baru)

tf.Tensor([[1 1 1 1 1 1]], shape=(1, 6), dtype=int32)


# Perbandingan Tensor dan Numpy

In [22]:
tensor = tf.zeros((2,2))

print(f"""Ini adalah hasil tensor:
{tensor}""")

numpy = np.zeros((2,2))

print(f"""Ini adalah hasil numpy:
{numpy}""")

Ini adalah hasil tensor:
[[0. 0.]
 [0. 0.]]
Ini adalah hasil numpy:
[[0. 0.]
 [0. 0.]]


# Operasi Matematika Dengan Tensor dan Numpy


In [23]:
tensor1 = tf.constant(2)
tensor2 = tf.constant(3)

print(tensor1*tensor2)

tf.Tensor(6, shape=(), dtype=int32)
